#!/usr/bin/env php
<?php
/**
 * @author      Laurent Jouanneau
 * @copyright   2019 Laurent Jouanneau
 * @licence     MIT
 */

require(__DIR__.'/vendor/autoload.php');

use Jelix\GandiApi\Configuration;
use Jelix\GandiApi\Command\Application;
use Jelix\GandiApi\Command\Status;
use Jelix\GandiApi\Command\LiveDns;


$apiKeyFile = __DIR__.'/.apikey';

if (!file_exists($apiKeyFile)) {
    echo "Error: .apikey is missing";
    exit(1);
}

$configuration = new Configuration(file_get_contents($apiKeyFile));


$application = new Application($configuration);
$application->add(new Status());
$application->add(new LiveDns\RecordsList());
$application->run();


